### PR TITLE
Spelling Correction

### PR DESCRIPTION
**Pull request by coloradopioneer**
Simple spelling correction in the docs.  Great CSS toolkit!

### CODE REVIEW

**Comment by pborreli** [comment]
you should propose the PR on the original repo https://github.com/primer/primer/, it's just a fork here

**Comment by pborreli** [comment]
thanks !

**Comment by pborreli** [comment]
ow and btw, I already proposed a PR fixing this particular typo https://github.com/primer/primer/pull/9

**Comment by coloradopioneer** [comment]
ohh I saw the other typo fix and must have missed this one! Thanks!

**Pull request closed without merging**
